// **********************************************************************
//
// Copyright (c) 2003-2013 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.5.1
//
// <auto-generated>
//
// Generated from file `LegController.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

#ifndef ____LegController_h__
#define ____LegController_h__

#include <Ice/ProxyF.h>
#include <Ice/ObjectF.h>
#include <Ice/Exception.h>
#include <Ice/LocalObject.h>
#include <Ice/StreamHelpers.h>
#include <Ice/Proxy.h>
#include <Ice/Object.h>
#include <Ice/Outgoing.h>
#include <Ice/OutgoingAsync.h>
#include <Ice/Incoming.h>
#include <Ice/Direct.h>
#include <IceUtil/ScopedArray.h>
#include <IceUtil/Optional.h>
#include <Ice/StreamF.h>
#include <Ice/UndefSysMacros.h>

#ifndef ICE_IGNORE_VERSION
#   if ICE_INT_VERSION / 100 != 305
#       error Ice version mismatch!
#   endif
#   if ICE_INT_VERSION % 100 > 50
#       error Beta header file detected
#   endif
#   if ICE_INT_VERSION % 100 < 1
#       error Ice patch level mismatch!
#   endif
#endif

namespace IceProxy
{

namespace RoboCompLegController
{

class LegController;
void __read(::IceInternal::BasicStream*, ::IceInternal::ProxyHandle< ::IceProxy::RoboCompLegController::LegController>&);
::IceProxy::Ice::Object* upCast(::IceProxy::RoboCompLegController::LegController*);

}

}

namespace RoboCompLegController
{

class LegController;
bool operator==(const LegController&, const LegController&);
bool operator<(const LegController&, const LegController&);
::Ice::Object* upCast(::RoboCompLegController::LegController*);
typedef ::IceInternal::Handle< ::RoboCompLegController::LegController> LegControllerPtr;
typedef ::IceInternal::ProxyHandle< ::IceProxy::RoboCompLegController::LegController> LegControllerPrx;
void __patch(LegControllerPtr&, const ::Ice::ObjectPtr&);

}

namespace RoboCompLegController
{

struct PoseLeg
{
    ::Ice::Float x;
    ::Ice::Float y;
    ::Ice::Float z;
    ::Ice::Float vel;
    ::std::string ref;
};

struct PoseBody
{
    ::Ice::Float rx;
    ::Ice::Float ry;
    ::Ice::Float rz;
    ::Ice::Float vel;
};

struct AnglesLeg
{
    ::Ice::Float q1;
    ::Ice::Float q2;
    ::Ice::Float q3;
    ::Ice::Float vel;
};

struct StateLeg
{
    ::Ice::Float posclavicula;
    ::Ice::Float poshombro;
    ::Ice::Float poscodo;
    ::Ice::Float x;
    ::Ice::Float y;
    ::Ice::Float z;
    ::std::string ref;
    bool ismoving;
};

typedef ::std::vector< ::RoboCompLegController::PoseLeg> ListPoseLeg;

}

namespace Ice
{
template<>
struct StreamableTraits< ::RoboCompLegController::PoseLeg>
{
    static const StreamHelperCategory helper = StreamHelperCategoryStruct;
    static const int minWireSize = 17;
    static const bool fixedLength = false;
};

template<class S>
struct StreamWriter< ::RoboCompLegController::PoseLeg, S>
{
    static void write(S* __os, const ::RoboCompLegController::PoseLeg& v)
    {
        __os->write(v.x);
        __os->write(v.y);
        __os->write(v.z);
        __os->write(v.vel);
        __os->write(v.ref);
    }
};

template<class S>
struct StreamReader< ::RoboCompLegController::PoseLeg, S>
{
    static void read(S* __is, ::RoboCompLegController::PoseLeg& v)
    {
        __is->read(v.x);
        __is->read(v.y);
        __is->read(v.z);
        __is->read(v.vel);
        __is->read(v.ref);
    }
};

template<>
struct StreamableTraits< ::RoboCompLegController::PoseBody>
{
    static const StreamHelperCategory helper = StreamHelperCategoryStruct;
    static const int minWireSize = 16;
    static const bool fixedLength = true;
};

template<class S>
struct StreamWriter< ::RoboCompLegController::PoseBody, S>
{
    static void write(S* __os, const ::RoboCompLegController::PoseBody& v)
    {
        __os->write(v.rx);
        __os->write(v.ry);
        __os->write(v.rz);
        __os->write(v.vel);
    }
};

template<class S>
struct StreamReader< ::RoboCompLegController::PoseBody, S>
{
    static void read(S* __is, ::RoboCompLegController::PoseBody& v)
    {
        __is->read(v.rx);
        __is->read(v.ry);
        __is->read(v.rz);
        __is->read(v.vel);
    }
};

template<>
struct StreamableTraits< ::RoboCompLegController::AnglesLeg>
{
    static const StreamHelperCategory helper = StreamHelperCategoryStruct;
    static const int minWireSize = 16;
    static const bool fixedLength = true;
};

template<class S>
struct StreamWriter< ::RoboCompLegController::AnglesLeg, S>
{
    static void write(S* __os, const ::RoboCompLegController::AnglesLeg& v)
    {
        __os->write(v.q1);
        __os->write(v.q2);
        __os->write(v.q3);
        __os->write(v.vel);
    }
};

template<class S>
struct StreamReader< ::RoboCompLegController::AnglesLeg, S>
{
    static void read(S* __is, ::RoboCompLegController::AnglesLeg& v)
    {
        __is->read(v.q1);
        __is->read(v.q2);
        __is->read(v.q3);
        __is->read(v.vel);
    }
};

template<>
struct StreamableTraits< ::RoboCompLegController::StateLeg>
{
    static const StreamHelperCategory helper = StreamHelperCategoryStruct;
    static const int minWireSize = 26;
    static const bool fixedLength = false;
};

template<class S>
struct StreamWriter< ::RoboCompLegController::StateLeg, S>
{
    static void write(S* __os, const ::RoboCompLegController::StateLeg& v)
    {
        __os->write(v.posclavicula);
        __os->write(v.poshombro);
        __os->write(v.poscodo);
        __os->write(v.x);
        __os->write(v.y);
        __os->write(v.z);
        __os->write(v.ref);
        __os->write(v.ismoving);
    }
};

template<class S>
struct StreamReader< ::RoboCompLegController::StateLeg, S>
{
    static void read(S* __is, ::RoboCompLegController::StateLeg& v)
    {
        __is->read(v.posclavicula);
        __is->read(v.poshombro);
        __is->read(v.poscodo);
        __is->read(v.x);
        __is->read(v.y);
        __is->read(v.z);
        __is->read(v.ref);
        __is->read(v.ismoving);
    }
};

}

namespace RoboCompLegController
{

class Callback_LegController_setListIKLeg_Base : virtual public ::IceInternal::CallbackBase { };
typedef ::IceUtil::Handle< Callback_LegController_setListIKLeg_Base> Callback_LegController_setListIKLegPtr;

class Callback_LegController_setIKLeg_Base : virtual public ::IceInternal::CallbackBase { };
typedef ::IceUtil::Handle< Callback_LegController_setIKLeg_Base> Callback_LegController_setIKLegPtr;

class Callback_LegController_setIKBody_Base : virtual public ::IceInternal::CallbackBase { };
typedef ::IceUtil::Handle< Callback_LegController_setIKBody_Base> Callback_LegController_setIKBodyPtr;

class Callback_LegController_setFKLeg_Base : virtual public ::IceInternal::CallbackBase { };
typedef ::IceUtil::Handle< Callback_LegController_setFKLeg_Base> Callback_LegController_setFKLegPtr;

class Callback_LegController_getStateLeg_Base : virtual public ::IceInternal::CallbackBase { };
typedef ::IceUtil::Handle< Callback_LegController_getStateLeg_Base> Callback_LegController_getStateLegPtr;

}

namespace IceProxy
{

namespace RoboCompLegController
{

class LegController : virtual public ::IceProxy::Ice::Object
{
public:

    void setListIKLeg(const ::RoboCompLegController::ListPoseLeg& ps)
    {
        setListIKLeg(ps, 0);
    }
    void setListIKLeg(const ::RoboCompLegController::ListPoseLeg& ps, const ::Ice::Context& __ctx)
    {
        setListIKLeg(ps, &__ctx);
    }
#ifdef ICE_CPP11
    ::Ice::AsyncResultPtr
    begin_setListIKLeg(const ::RoboCompLegController::ListPoseLeg& ps, const ::IceInternal::Function<void ()>& __response, const ::IceInternal::Function<void (const ::Ice::Exception&)>& __exception = ::IceInternal::Function<void (const ::Ice::Exception&)>(), const ::IceInternal::Function<void (bool)>& __sent = ::IceInternal::Function<void (bool)>())
    {
        return begin_setListIKLeg(ps, 0, new ::IceInternal::Cpp11FnOnewayCallbackNC(__response, __exception, __sent));
    }
    ::Ice::AsyncResultPtr
    begin_setListIKLeg(const ::RoboCompLegController::ListPoseLeg& ps, const ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>& __completed, const ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>& __sent = ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>())
    {
        return begin_setListIKLeg(ps, 0, ::Ice::newCallback(__completed, __sent), 0);
    }
    ::Ice::AsyncResultPtr
    begin_setListIKLeg(const ::RoboCompLegController::ListPoseLeg& ps, const ::Ice::Context& __ctx, const ::IceInternal::Function<void ()>& __response, const ::IceInternal::Function<void (const ::Ice::Exception&)>& __exception = ::IceInternal::Function<void (const ::Ice::Exception&)>(), const ::IceInternal::Function<void (bool)>& __sent = ::IceInternal::Function<void (bool)>())
    {
        return begin_setListIKLeg(ps, &__ctx, new ::IceInternal::Cpp11FnOnewayCallbackNC(__response, __exception, __sent), 0);
    }
    ::Ice::AsyncResultPtr
    begin_setListIKLeg(const ::RoboCompLegController::ListPoseLeg& ps, const ::Ice::Context& __ctx, const ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>& __completed, const ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>& __sent = ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>())
    {
        return begin_setListIKLeg(ps, &__ctx, ::Ice::newCallback(__completed, __sent));
    }
#endif

    ::Ice::AsyncResultPtr begin_setListIKLeg(const ::RoboCompLegController::ListPoseLeg& ps)
    {
        return begin_setListIKLeg(ps, 0, ::IceInternal::__dummyCallback, 0);
    }

    ::Ice::AsyncResultPtr begin_setListIKLeg(const ::RoboCompLegController::ListPoseLeg& ps, const ::Ice::Context& __ctx)
    {
        return begin_setListIKLeg(ps, &__ctx, ::IceInternal::__dummyCallback, 0);
    }

    ::Ice::AsyncResultPtr begin_setListIKLeg(const ::RoboCompLegController::ListPoseLeg& ps, const ::Ice::CallbackPtr& __del, const ::Ice::LocalObjectPtr& __cookie = 0)
    {
        return begin_setListIKLeg(ps, 0, __del, __cookie);
    }

    ::Ice::AsyncResultPtr begin_setListIKLeg(const ::RoboCompLegController::ListPoseLeg& ps, const ::Ice::Context& __ctx, const ::Ice::CallbackPtr& __del, const ::Ice::LocalObjectPtr& __cookie = 0)
    {
        return begin_setListIKLeg(ps, &__ctx, __del, __cookie);
    }

    ::Ice::AsyncResultPtr begin_setListIKLeg(const ::RoboCompLegController::ListPoseLeg& ps, const ::RoboCompLegController::Callback_LegController_setListIKLegPtr& __del, const ::Ice::LocalObjectPtr& __cookie = 0)
    {
        return begin_setListIKLeg(ps, 0, __del, __cookie);
    }

    ::Ice::AsyncResultPtr begin_setListIKLeg(const ::RoboCompLegController::ListPoseLeg& ps, const ::Ice::Context& __ctx, const ::RoboCompLegController::Callback_LegController_setListIKLegPtr& __del, const ::Ice::LocalObjectPtr& __cookie = 0)
    {
        return begin_setListIKLeg(ps, &__ctx, __del, __cookie);
    }

    void end_setListIKLeg(const ::Ice::AsyncResultPtr&);
    
private:

    void setListIKLeg(const ::RoboCompLegController::ListPoseLeg&, const ::Ice::Context*);
    ::Ice::AsyncResultPtr begin_setListIKLeg(const ::RoboCompLegController::ListPoseLeg&, const ::Ice::Context*, const ::IceInternal::CallbackBasePtr&, const ::Ice::LocalObjectPtr& __cookie = 0);
    
public:

    void setIKLeg(const ::RoboCompLegController::PoseLeg& p)
    {
        setIKLeg(p, 0);
    }
    void setIKLeg(const ::RoboCompLegController::PoseLeg& p, const ::Ice::Context& __ctx)
    {
        setIKLeg(p, &__ctx);
    }
#ifdef ICE_CPP11
    ::Ice::AsyncResultPtr
    begin_setIKLeg(const ::RoboCompLegController::PoseLeg& p, const ::IceInternal::Function<void ()>& __response, const ::IceInternal::Function<void (const ::Ice::Exception&)>& __exception = ::IceInternal::Function<void (const ::Ice::Exception&)>(), const ::IceInternal::Function<void (bool)>& __sent = ::IceInternal::Function<void (bool)>())
    {
        return begin_setIKLeg(p, 0, new ::IceInternal::Cpp11FnOnewayCallbackNC(__response, __exception, __sent));
    }
    ::Ice::AsyncResultPtr
    begin_setIKLeg(const ::RoboCompLegController::PoseLeg& p, const ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>& __completed, const ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>& __sent = ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>())
    {
        return begin_setIKLeg(p, 0, ::Ice::newCallback(__completed, __sent), 0);
    }
    ::Ice::AsyncResultPtr
    begin_setIKLeg(const ::RoboCompLegController::PoseLeg& p, const ::Ice::Context& __ctx, const ::IceInternal::Function<void ()>& __response, const ::IceInternal::Function<void (const ::Ice::Exception&)>& __exception = ::IceInternal::Function<void (const ::Ice::Exception&)>(), const ::IceInternal::Function<void (bool)>& __sent = ::IceInternal::Function<void (bool)>())
    {
        return begin_setIKLeg(p, &__ctx, new ::IceInternal::Cpp11FnOnewayCallbackNC(__response, __exception, __sent), 0);
    }
    ::Ice::AsyncResultPtr
    begin_setIKLeg(const ::RoboCompLegController::PoseLeg& p, const ::Ice::Context& __ctx, const ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>& __completed, const ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>& __sent = ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>())
    {
        return begin_setIKLeg(p, &__ctx, ::Ice::newCallback(__completed, __sent));
    }
#endif

    ::Ice::AsyncResultPtr begin_setIKLeg(const ::RoboCompLegController::PoseLeg& p)
    {
        return begin_setIKLeg(p, 0, ::IceInternal::__dummyCallback, 0);
    }

    ::Ice::AsyncResultPtr begin_setIKLeg(const ::RoboCompLegController::PoseLeg& p, const ::Ice::Context& __ctx)
    {
        return begin_setIKLeg(p, &__ctx, ::IceInternal::__dummyCallback, 0);
    }

    ::Ice::AsyncResultPtr begin_setIKLeg(const ::RoboCompLegController::PoseLeg& p, const ::Ice::CallbackPtr& __del, const ::Ice::LocalObjectPtr& __cookie = 0)
    {
        return begin_setIKLeg(p, 0, __del, __cookie);
    }

    ::Ice::AsyncResultPtr begin_setIKLeg(const ::RoboCompLegController::PoseLeg& p, const ::Ice::Context& __ctx, const ::Ice::CallbackPtr& __del, const ::Ice::LocalObjectPtr& __cookie = 0)
    {
        return begin_setIKLeg(p, &__ctx, __del, __cookie);
    }

    ::Ice::AsyncResultPtr begin_setIKLeg(const ::RoboCompLegController::PoseLeg& p, const ::RoboCompLegController::Callback_LegController_setIKLegPtr& __del, const ::Ice::LocalObjectPtr& __cookie = 0)
    {
        return begin_setIKLeg(p, 0, __del, __cookie);
    }

    ::Ice::AsyncResultPtr begin_setIKLeg(const ::RoboCompLegController::PoseLeg& p, const ::Ice::Context& __ctx, const ::RoboCompLegController::Callback_LegController_setIKLegPtr& __del, const ::Ice::LocalObjectPtr& __cookie = 0)
    {
        return begin_setIKLeg(p, &__ctx, __del, __cookie);
    }

    void end_setIKLeg(const ::Ice::AsyncResultPtr&);
    
private:

    void setIKLeg(const ::RoboCompLegController::PoseLeg&, const ::Ice::Context*);
    ::Ice::AsyncResultPtr begin_setIKLeg(const ::RoboCompLegController::PoseLeg&, const ::Ice::Context*, const ::IceInternal::CallbackBasePtr&, const ::Ice::LocalObjectPtr& __cookie = 0);
    
public:

    void setIKBody(const ::RoboCompLegController::PoseBody& p)
    {
        setIKBody(p, 0);
    }
    void setIKBody(const ::RoboCompLegController::PoseBody& p, const ::Ice::Context& __ctx)
    {
        setIKBody(p, &__ctx);
    }
#ifdef ICE_CPP11
    ::Ice::AsyncResultPtr
    begin_setIKBody(const ::RoboCompLegController::PoseBody& p, const ::IceInternal::Function<void ()>& __response, const ::IceInternal::Function<void (const ::Ice::Exception&)>& __exception = ::IceInternal::Function<void (const ::Ice::Exception&)>(), const ::IceInternal::Function<void (bool)>& __sent = ::IceInternal::Function<void (bool)>())
    {
        return begin_setIKBody(p, 0, new ::IceInternal::Cpp11FnOnewayCallbackNC(__response, __exception, __sent));
    }
    ::Ice::AsyncResultPtr
    begin_setIKBody(const ::RoboCompLegController::PoseBody& p, const ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>& __completed, const ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>& __sent = ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>())
    {
        return begin_setIKBody(p, 0, ::Ice::newCallback(__completed, __sent), 0);
    }
    ::Ice::AsyncResultPtr
    begin_setIKBody(const ::RoboCompLegController::PoseBody& p, const ::Ice::Context& __ctx, const ::IceInternal::Function<void ()>& __response, const ::IceInternal::Function<void (const ::Ice::Exception&)>& __exception = ::IceInternal::Function<void (const ::Ice::Exception&)>(), const ::IceInternal::Function<void (bool)>& __sent = ::IceInternal::Function<void (bool)>())
    {
        return begin_setIKBody(p, &__ctx, new ::IceInternal::Cpp11FnOnewayCallbackNC(__response, __exception, __sent), 0);
    }
    ::Ice::AsyncResultPtr
    begin_setIKBody(const ::RoboCompLegController::PoseBody& p, const ::Ice::Context& __ctx, const ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>& __completed, const ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>& __sent = ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>())
    {
        return begin_setIKBody(p, &__ctx, ::Ice::newCallback(__completed, __sent));
    }
#endif

    ::Ice::AsyncResultPtr begin_setIKBody(const ::RoboCompLegController::PoseBody& p)
    {
        return begin_setIKBody(p, 0, ::IceInternal::__dummyCallback, 0);
    }

    ::Ice::AsyncResultPtr begin_setIKBody(const ::RoboCompLegController::PoseBody& p, const ::Ice::Context& __ctx)
    {
        return begin_setIKBody(p, &__ctx, ::IceInternal::__dummyCallback, 0);
    }

    ::Ice::AsyncResultPtr begin_setIKBody(const ::RoboCompLegController::PoseBody& p, const ::Ice::CallbackPtr& __del, const ::Ice::LocalObjectPtr& __cookie = 0)
    {
        return begin_setIKBody(p, 0, __del, __cookie);
    }

    ::Ice::AsyncResultPtr begin_setIKBody(const ::RoboCompLegController::PoseBody& p, const ::Ice::Context& __ctx, const ::Ice::CallbackPtr& __del, const ::Ice::LocalObjectPtr& __cookie = 0)
    {
        return begin_setIKBody(p, &__ctx, __del, __cookie);
    }

    ::Ice::AsyncResultPtr begin_setIKBody(const ::RoboCompLegController::PoseBody& p, const ::RoboCompLegController::Callback_LegController_setIKBodyPtr& __del, const ::Ice::LocalObjectPtr& __cookie = 0)
    {
        return begin_setIKBody(p, 0, __del, __cookie);
    }

    ::Ice::AsyncResultPtr begin_setIKBody(const ::RoboCompLegController::PoseBody& p, const ::Ice::Context& __ctx, const ::RoboCompLegController::Callback_LegController_setIKBodyPtr& __del, const ::Ice::LocalObjectPtr& __cookie = 0)
    {
        return begin_setIKBody(p, &__ctx, __del, __cookie);
    }

    void end_setIKBody(const ::Ice::AsyncResultPtr&);
    
private:

    void setIKBody(const ::RoboCompLegController::PoseBody&, const ::Ice::Context*);
    ::Ice::AsyncResultPtr begin_setIKBody(const ::RoboCompLegController::PoseBody&, const ::Ice::Context*, const ::IceInternal::CallbackBasePtr&, const ::Ice::LocalObjectPtr& __cookie = 0);
    
public:

    void setFKLeg(const ::RoboCompLegController::AnglesLeg& al)
    {
        setFKLeg(al, 0);
    }
    void setFKLeg(const ::RoboCompLegController::AnglesLeg& al, const ::Ice::Context& __ctx)
    {
        setFKLeg(al, &__ctx);
    }
#ifdef ICE_CPP11
    ::Ice::AsyncResultPtr
    begin_setFKLeg(const ::RoboCompLegController::AnglesLeg& al, const ::IceInternal::Function<void ()>& __response, const ::IceInternal::Function<void (const ::Ice::Exception&)>& __exception = ::IceInternal::Function<void (const ::Ice::Exception&)>(), const ::IceInternal::Function<void (bool)>& __sent = ::IceInternal::Function<void (bool)>())
    {
        return begin_setFKLeg(al, 0, new ::IceInternal::Cpp11FnOnewayCallbackNC(__response, __exception, __sent));
    }
    ::Ice::AsyncResultPtr
    begin_setFKLeg(const ::RoboCompLegController::AnglesLeg& al, const ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>& __completed, const ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>& __sent = ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>())
    {
        return begin_setFKLeg(al, 0, ::Ice::newCallback(__completed, __sent), 0);
    }
    ::Ice::AsyncResultPtr
    begin_setFKLeg(const ::RoboCompLegController::AnglesLeg& al, const ::Ice::Context& __ctx, const ::IceInternal::Function<void ()>& __response, const ::IceInternal::Function<void (const ::Ice::Exception&)>& __exception = ::IceInternal::Function<void (const ::Ice::Exception&)>(), const ::IceInternal::Function<void (bool)>& __sent = ::IceInternal::Function<void (bool)>())
    {
        return begin_setFKLeg(al, &__ctx, new ::IceInternal::Cpp11FnOnewayCallbackNC(__response, __exception, __sent), 0);
    }
    ::Ice::AsyncResultPtr
    begin_setFKLeg(const ::RoboCompLegController::AnglesLeg& al, const ::Ice::Context& __ctx, const ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>& __completed, const ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>& __sent = ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>())
    {
        return begin_setFKLeg(al, &__ctx, ::Ice::newCallback(__completed, __sent));
    }
#endif

    ::Ice::AsyncResultPtr begin_setFKLeg(const ::RoboCompLegController::AnglesLeg& al)
    {
        return begin_setFKLeg(al, 0, ::IceInternal::__dummyCallback, 0);
    }

    ::Ice::AsyncResultPtr begin_setFKLeg(const ::RoboCompLegController::AnglesLeg& al, const ::Ice::Context& __ctx)
    {
        return begin_setFKLeg(al, &__ctx, ::IceInternal::__dummyCallback, 0);
    }

    ::Ice::AsyncResultPtr begin_setFKLeg(const ::RoboCompLegController::AnglesLeg& al, const ::Ice::CallbackPtr& __del, const ::Ice::LocalObjectPtr& __cookie = 0)
    {
        return begin_setFKLeg(al, 0, __del, __cookie);
    }

    ::Ice::AsyncResultPtr begin_setFKLeg(const ::RoboCompLegController::AnglesLeg& al, const ::Ice::Context& __ctx, const ::Ice::CallbackPtr& __del, const ::Ice::LocalObjectPtr& __cookie = 0)
    {
        return begin_setFKLeg(al, &__ctx, __del, __cookie);
    }

    ::Ice::AsyncResultPtr begin_setFKLeg(const ::RoboCompLegController::AnglesLeg& al, const ::RoboCompLegController::Callback_LegController_setFKLegPtr& __del, const ::Ice::LocalObjectPtr& __cookie = 0)
    {
        return begin_setFKLeg(al, 0, __del, __cookie);
    }

    ::Ice::AsyncResultPtr begin_setFKLeg(const ::RoboCompLegController::AnglesLeg& al, const ::Ice::Context& __ctx, const ::RoboCompLegController::Callback_LegController_setFKLegPtr& __del, const ::Ice::LocalObjectPtr& __cookie = 0)
    {
        return begin_setFKLeg(al, &__ctx, __del, __cookie);
    }

    void end_setFKLeg(const ::Ice::AsyncResultPtr&);
    
private:

    void setFKLeg(const ::RoboCompLegController::AnglesLeg&, const ::Ice::Context*);
    ::Ice::AsyncResultPtr begin_setFKLeg(const ::RoboCompLegController::AnglesLeg&, const ::Ice::Context*, const ::IceInternal::CallbackBasePtr&, const ::Ice::LocalObjectPtr& __cookie = 0);
    
public:

    ::RoboCompLegController::StateLeg getStateLeg()
    {
        return getStateLeg(0);
    }
    ::RoboCompLegController::StateLeg getStateLeg(const ::Ice::Context& __ctx)
    {
        return getStateLeg(&__ctx);
    }
#ifdef ICE_CPP11
    ::Ice::AsyncResultPtr
    begin_getStateLeg(const ::IceInternal::Function<void (const ::RoboCompLegController::StateLeg&)>& __response, const ::IceInternal::Function<void (const ::Ice::Exception&)>& __exception = ::IceInternal::Function<void (const ::Ice::Exception&)>(), const ::IceInternal::Function<void (bool)>& __sent = ::IceInternal::Function<void (bool)>())
    {
        return __begin_getStateLeg(0, __response, __exception, __sent);
    }
    ::Ice::AsyncResultPtr
    begin_getStateLeg(const ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>& __completed, const ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>& __sent = ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>())
    {
        return begin_getStateLeg(0, ::Ice::newCallback(__completed, __sent), 0);
    }
    ::Ice::AsyncResultPtr
    begin_getStateLeg(const ::Ice::Context& __ctx, const ::IceInternal::Function<void (const ::RoboCompLegController::StateLeg&)>& __response, const ::IceInternal::Function<void (const ::Ice::Exception&)>& __exception = ::IceInternal::Function<void (const ::Ice::Exception&)>(), const ::IceInternal::Function<void (bool)>& __sent = ::IceInternal::Function<void (bool)>())
    {
        return __begin_getStateLeg(&__ctx, __response, __exception, __sent);
    }
    ::Ice::AsyncResultPtr
    begin_getStateLeg(const ::Ice::Context& __ctx, const ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>& __completed, const ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>& __sent = ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>())
    {
        return begin_getStateLeg(&__ctx, ::Ice::newCallback(__completed, __sent));
    }
    
private:

    ::Ice::AsyncResultPtr __begin_getStateLeg(const ::Ice::Context* __ctx, const ::IceInternal::Function<void (const ::RoboCompLegController::StateLeg&)>& __response, const ::IceInternal::Function<void (const ::Ice::Exception&)>& __exception, const ::IceInternal::Function<void (bool)>& __sent)
    {
        class Cpp11CB : public ::IceInternal::Cpp11FnCallbackNC
        {
        public:

            Cpp11CB(const ::std::function<void (const ::RoboCompLegController::StateLeg&)>& responseFunc, const ::std::function<void (const ::Ice::Exception&)>& exceptionFunc, const ::std::function<void (bool)>& sentFunc) :
                ::IceInternal::Cpp11FnCallbackNC(exceptionFunc, sentFunc),
                _response(responseFunc)
            {
                CallbackBase::checkCallback(true, responseFunc || exceptionFunc != nullptr);
            }

            virtual void __completed(const ::Ice::AsyncResultPtr& __result) const
            {
                ::RoboCompLegController::LegControllerPrx __proxy = ::RoboCompLegController::LegControllerPrx::uncheckedCast(__result->getProxy());
                ::RoboCompLegController::StateLeg __ret;
                try
                {
                    __ret = __proxy->end_getStateLeg(__result);
                }
                catch(::Ice::Exception& ex)
                {
                    Cpp11FnCallbackNC::__exception(__result, ex);
                    return;
                }
                if(_response != nullptr)
                {
                    _response(__ret);
                }
            }
        
        private:
            
            ::std::function<void (const ::RoboCompLegController::StateLeg&)> _response;
        };
        return begin_getStateLeg(__ctx, new Cpp11CB(__response, __exception, __sent));
    }
    
public:
#endif

    ::Ice::AsyncResultPtr begin_getStateLeg()
    {
        return begin_getStateLeg(0, ::IceInternal::__dummyCallback, 0);
    }

    ::Ice::AsyncResultPtr begin_getStateLeg(const ::Ice::Context& __ctx)
    {
        return begin_getStateLeg(&__ctx, ::IceInternal::__dummyCallback, 0);
    }

    ::Ice::AsyncResultPtr begin_getStateLeg(const ::Ice::CallbackPtr& __del, const ::Ice::LocalObjectPtr& __cookie = 0)
    {
        return begin_getStateLeg(0, __del, __cookie);
    }

    ::Ice::AsyncResultPtr begin_getStateLeg(const ::Ice::Context& __ctx, const ::Ice::CallbackPtr& __del, const ::Ice::LocalObjectPtr& __cookie = 0)
    {
        return begin_getStateLeg(&__ctx, __del, __cookie);
    }

    ::Ice::AsyncResultPtr begin_getStateLeg(const ::RoboCompLegController::Callback_LegController_getStateLegPtr& __del, const ::Ice::LocalObjectPtr& __cookie = 0)
    {
        return begin_getStateLeg(0, __del, __cookie);
    }

    ::Ice::AsyncResultPtr begin_getStateLeg(const ::Ice::Context& __ctx, const ::RoboCompLegController::Callback_LegController_getStateLegPtr& __del, const ::Ice::LocalObjectPtr& __cookie = 0)
    {
        return begin_getStateLeg(&__ctx, __del, __cookie);
    }

    ::RoboCompLegController::StateLeg end_getStateLeg(const ::Ice::AsyncResultPtr&);
    
private:

    ::RoboCompLegController::StateLeg getStateLeg(const ::Ice::Context*);
    ::Ice::AsyncResultPtr begin_getStateLeg(const ::Ice::Context*, const ::IceInternal::CallbackBasePtr&, const ::Ice::LocalObjectPtr& __cookie = 0);
    
public:
    
    ::IceInternal::ProxyHandle<LegController> ice_context(const ::Ice::Context& __context) const
    {
        return dynamic_cast<LegController*>(::IceProxy::Ice::Object::ice_context(__context).get());
    }
    
    ::IceInternal::ProxyHandle<LegController> ice_adapterId(const ::std::string& __id) const
    {
        return dynamic_cast<LegController*>(::IceProxy::Ice::Object::ice_adapterId(__id).get());
    }
    
    ::IceInternal::ProxyHandle<LegController> ice_endpoints(const ::Ice::EndpointSeq& __endpoints) const
    {
        return dynamic_cast<LegController*>(::IceProxy::Ice::Object::ice_endpoints(__endpoints).get());
    }
    
    ::IceInternal::ProxyHandle<LegController> ice_locatorCacheTimeout(int __timeout) const
    {
        return dynamic_cast<LegController*>(::IceProxy::Ice::Object::ice_locatorCacheTimeout(__timeout).get());
    }
    
    ::IceInternal::ProxyHandle<LegController> ice_connectionCached(bool __cached) const
    {
        return dynamic_cast<LegController*>(::IceProxy::Ice::Object::ice_connectionCached(__cached).get());
    }
    
    ::IceInternal::ProxyHandle<LegController> ice_endpointSelection(::Ice::EndpointSelectionType __est) const
    {
        return dynamic_cast<LegController*>(::IceProxy::Ice::Object::ice_endpointSelection(__est).get());
    }
    
    ::IceInternal::ProxyHandle<LegController> ice_secure(bool __secure) const
    {
        return dynamic_cast<LegController*>(::IceProxy::Ice::Object::ice_secure(__secure).get());
    }
    
    ::IceInternal::ProxyHandle<LegController> ice_preferSecure(bool __preferSecure) const
    {
        return dynamic_cast<LegController*>(::IceProxy::Ice::Object::ice_preferSecure(__preferSecure).get());
    }
    
    ::IceInternal::ProxyHandle<LegController> ice_router(const ::Ice::RouterPrx& __router) const
    {
        return dynamic_cast<LegController*>(::IceProxy::Ice::Object::ice_router(__router).get());
    }
    
    ::IceInternal::ProxyHandle<LegController> ice_locator(const ::Ice::LocatorPrx& __locator) const
    {
        return dynamic_cast<LegController*>(::IceProxy::Ice::Object::ice_locator(__locator).get());
    }
    
    ::IceInternal::ProxyHandle<LegController> ice_collocationOptimized(bool __co) const
    {
        return dynamic_cast<LegController*>(::IceProxy::Ice::Object::ice_collocationOptimized(__co).get());
    }
    
    ::IceInternal::ProxyHandle<LegController> ice_twoway() const
    {
        return dynamic_cast<LegController*>(::IceProxy::Ice::Object::ice_twoway().get());
    }
    
    ::IceInternal::ProxyHandle<LegController> ice_oneway() const
    {
        return dynamic_cast<LegController*>(::IceProxy::Ice::Object::ice_oneway().get());
    }
    
    ::IceInternal::ProxyHandle<LegController> ice_batchOneway() const
    {
        return dynamic_cast<LegController*>(::IceProxy::Ice::Object::ice_batchOneway().get());
    }
    
    ::IceInternal::ProxyHandle<LegController> ice_datagram() const
    {
        return dynamic_cast<LegController*>(::IceProxy::Ice::Object::ice_datagram().get());
    }
    
    ::IceInternal::ProxyHandle<LegController> ice_batchDatagram() const
    {
        return dynamic_cast<LegController*>(::IceProxy::Ice::Object::ice_batchDatagram().get());
    }
    
    ::IceInternal::ProxyHandle<LegController> ice_compress(bool __compress) const
    {
        return dynamic_cast<LegController*>(::IceProxy::Ice::Object::ice_compress(__compress).get());
    }
    
    ::IceInternal::ProxyHandle<LegController> ice_timeout(int __timeout) const
    {
        return dynamic_cast<LegController*>(::IceProxy::Ice::Object::ice_timeout(__timeout).get());
    }
    
    ::IceInternal::ProxyHandle<LegController> ice_connectionId(const ::std::string& __id) const
    {
        return dynamic_cast<LegController*>(::IceProxy::Ice::Object::ice_connectionId(__id).get());
    }
    
    ::IceInternal::ProxyHandle<LegController> ice_encodingVersion(const ::Ice::EncodingVersion& __v) const
    {
        return dynamic_cast<LegController*>(::IceProxy::Ice::Object::ice_encodingVersion(__v).get());
    }
    
    static const ::std::string& ice_staticId();

private: 

    virtual ::IceInternal::Handle< ::IceDelegateM::Ice::Object> __createDelegateM();
    virtual ::IceInternal::Handle< ::IceDelegateD::Ice::Object> __createDelegateD();
    virtual ::IceProxy::Ice::Object* __newInstance() const;
};

}

}

namespace IceDelegate
{

namespace RoboCompLegController
{

class LegController : virtual public ::IceDelegate::Ice::Object
{
public:

    virtual void setListIKLeg(const ::RoboCompLegController::ListPoseLeg&, const ::Ice::Context*, ::IceInternal::InvocationObserver&) = 0;

    virtual void setIKLeg(const ::RoboCompLegController::PoseLeg&, const ::Ice::Context*, ::IceInternal::InvocationObserver&) = 0;

    virtual void setIKBody(const ::RoboCompLegController::PoseBody&, const ::Ice::Context*, ::IceInternal::InvocationObserver&) = 0;

    virtual void setFKLeg(const ::RoboCompLegController::AnglesLeg&, const ::Ice::Context*, ::IceInternal::InvocationObserver&) = 0;

    virtual ::RoboCompLegController::StateLeg getStateLeg(const ::Ice::Context*, ::IceInternal::InvocationObserver&) = 0;
};

}

}

namespace IceDelegateM
{

namespace RoboCompLegController
{

class LegController : virtual public ::IceDelegate::RoboCompLegController::LegController,
                      virtual public ::IceDelegateM::Ice::Object
{
public:

    virtual void setListIKLeg(const ::RoboCompLegController::ListPoseLeg&, const ::Ice::Context*, ::IceInternal::InvocationObserver&);

    virtual void setIKLeg(const ::RoboCompLegController::PoseLeg&, const ::Ice::Context*, ::IceInternal::InvocationObserver&);

    virtual void setIKBody(const ::RoboCompLegController::PoseBody&, const ::Ice::Context*, ::IceInternal::InvocationObserver&);

    virtual void setFKLeg(const ::RoboCompLegController::AnglesLeg&, const ::Ice::Context*, ::IceInternal::InvocationObserver&);

    virtual ::RoboCompLegController::StateLeg getStateLeg(const ::Ice::Context*, ::IceInternal::InvocationObserver&);
};

}

}

namespace IceDelegateD
{

namespace RoboCompLegController
{

class LegController : virtual public ::IceDelegate::RoboCompLegController::LegController,
                      virtual public ::IceDelegateD::Ice::Object
{
public:

    virtual void setListIKLeg(const ::RoboCompLegController::ListPoseLeg&, const ::Ice::Context*, ::IceInternal::InvocationObserver&);

    virtual void setIKLeg(const ::RoboCompLegController::PoseLeg&, const ::Ice::Context*, ::IceInternal::InvocationObserver&);

    virtual void setIKBody(const ::RoboCompLegController::PoseBody&, const ::Ice::Context*, ::IceInternal::InvocationObserver&);

    virtual void setFKLeg(const ::RoboCompLegController::AnglesLeg&, const ::Ice::Context*, ::IceInternal::InvocationObserver&);

    virtual ::RoboCompLegController::StateLeg getStateLeg(const ::Ice::Context*, ::IceInternal::InvocationObserver&);
};

}

}

namespace RoboCompLegController
{

class LegController : virtual public ::Ice::Object
{
public:

    typedef LegControllerPrx ProxyType;
    typedef LegControllerPtr PointerType;

    virtual bool ice_isA(const ::std::string&, const ::Ice::Current& = ::Ice::Current()) const;
    virtual ::std::vector< ::std::string> ice_ids(const ::Ice::Current& = ::Ice::Current()) const;
    virtual const ::std::string& ice_id(const ::Ice::Current& = ::Ice::Current()) const;
    static const ::std::string& ice_staticId();

    virtual void setListIKLeg(const ::RoboCompLegController::ListPoseLeg&, const ::Ice::Current& = ::Ice::Current()) = 0;
    ::Ice::DispatchStatus ___setListIKLeg(::IceInternal::Incoming&, const ::Ice::Current&);

    virtual void setIKLeg(const ::RoboCompLegController::PoseLeg&, const ::Ice::Current& = ::Ice::Current()) = 0;
    ::Ice::DispatchStatus ___setIKLeg(::IceInternal::Incoming&, const ::Ice::Current&);

    virtual void setIKBody(const ::RoboCompLegController::PoseBody&, const ::Ice::Current& = ::Ice::Current()) = 0;
    ::Ice::DispatchStatus ___setIKBody(::IceInternal::Incoming&, const ::Ice::Current&);

    virtual void setFKLeg(const ::RoboCompLegController::AnglesLeg&, const ::Ice::Current& = ::Ice::Current()) = 0;
    ::Ice::DispatchStatus ___setFKLeg(::IceInternal::Incoming&, const ::Ice::Current&);

    virtual ::RoboCompLegController::StateLeg getStateLeg(const ::Ice::Current& = ::Ice::Current()) = 0;
    ::Ice::DispatchStatus ___getStateLeg(::IceInternal::Incoming&, const ::Ice::Current&);

    virtual ::Ice::DispatchStatus __dispatch(::IceInternal::Incoming&, const ::Ice::Current&);

protected:
    virtual void __writeImpl(::IceInternal::BasicStream*) const;
    virtual void __readImpl(::IceInternal::BasicStream*);
    #ifdef __SUNPRO_CC
    using ::Ice::Object::__writeImpl;
    using ::Ice::Object::__readImpl;
    #endif
};

inline bool operator==(const LegController& l, const LegController& r)
{
    return static_cast<const ::Ice::Object&>(l) == static_cast<const ::Ice::Object&>(r);
}

inline bool operator<(const LegController& l, const LegController& r)
{
    return static_cast<const ::Ice::Object&>(l) < static_cast<const ::Ice::Object&>(r);
}

}

namespace RoboCompLegController
{

template<class T>
class CallbackNC_LegController_setListIKLeg : public Callback_LegController_setListIKLeg_Base, public ::IceInternal::OnewayCallbackNC<T>
{
public:

    typedef IceUtil::Handle<T> TPtr;

    typedef void (T::*Exception)(const ::Ice::Exception&);
    typedef void (T::*Sent)(bool);
    typedef void (T::*Response)();

    CallbackNC_LegController_setListIKLeg(const TPtr& obj, Response cb, Exception excb, Sent sentcb)
        : ::IceInternal::OnewayCallbackNC<T>(obj, cb, excb, sentcb)
    {
    }
};

template<class T> Callback_LegController_setListIKLegPtr
newCallback_LegController_setListIKLeg(const IceUtil::Handle<T>& instance, void (T::*cb)(), void (T::*excb)(const ::Ice::Exception&), void (T::*sentcb)(bool) = 0)
{
    return new CallbackNC_LegController_setListIKLeg<T>(instance, cb, excb, sentcb);
}

template<class T> Callback_LegController_setListIKLegPtr
newCallback_LegController_setListIKLeg(const IceUtil::Handle<T>& instance, void (T::*excb)(const ::Ice::Exception&), void (T::*sentcb)(bool) = 0)
{
    return new CallbackNC_LegController_setListIKLeg<T>(instance, 0, excb, sentcb);
}

template<class T> Callback_LegController_setListIKLegPtr
newCallback_LegController_setListIKLeg(T* instance, void (T::*cb)(), void (T::*excb)(const ::Ice::Exception&), void (T::*sentcb)(bool) = 0)
{
    return new CallbackNC_LegController_setListIKLeg<T>(instance, cb, excb, sentcb);
}

template<class T> Callback_LegController_setListIKLegPtr
newCallback_LegController_setListIKLeg(T* instance, void (T::*excb)(const ::Ice::Exception&), void (T::*sentcb)(bool) = 0)
{
    return new CallbackNC_LegController_setListIKLeg<T>(instance, 0, excb, sentcb);
}

template<class T, typename CT>
class Callback_LegController_setListIKLeg : public Callback_LegController_setListIKLeg_Base, public ::IceInternal::OnewayCallback<T, CT>
{
public:

    typedef IceUtil::Handle<T> TPtr;

    typedef void (T::*Exception)(const ::Ice::Exception& , const CT&);
    typedef void (T::*Sent)(bool , const CT&);
    typedef void (T::*Response)(const CT&);

    Callback_LegController_setListIKLeg(const TPtr& obj, Response cb, Exception excb, Sent sentcb)
        : ::IceInternal::OnewayCallback<T, CT>(obj, cb, excb, sentcb)
    {
    }
};

template<class T, typename CT> Callback_LegController_setListIKLegPtr
newCallback_LegController_setListIKLeg(const IceUtil::Handle<T>& instance, void (T::*cb)(const CT&), void (T::*excb)(const ::Ice::Exception&, const CT&), void (T::*sentcb)(bool, const CT&) = 0)
{
    return new Callback_LegController_setListIKLeg<T, CT>(instance, cb, excb, sentcb);
}

template<class T, typename CT> Callback_LegController_setListIKLegPtr
newCallback_LegController_setListIKLeg(const IceUtil::Handle<T>& instance, void (T::*excb)(const ::Ice::Exception&, const CT&), void (T::*sentcb)(bool, const CT&) = 0)
{
    return new Callback_LegController_setListIKLeg<T, CT>(instance, 0, excb, sentcb);
}

template<class T, typename CT> Callback_LegController_setListIKLegPtr
newCallback_LegController_setListIKLeg(T* instance, void (T::*cb)(const CT&), void (T::*excb)(const ::Ice::Exception&, const CT&), void (T::*sentcb)(bool, const CT&) = 0)
{
    return new Callback_LegController_setListIKLeg<T, CT>(instance, cb, excb, sentcb);
}

template<class T, typename CT> Callback_LegController_setListIKLegPtr
newCallback_LegController_setListIKLeg(T* instance, void (T::*excb)(const ::Ice::Exception&, const CT&), void (T::*sentcb)(bool, const CT&) = 0)
{
    return new Callback_LegController_setListIKLeg<T, CT>(instance, 0, excb, sentcb);
}

template<class T>
class CallbackNC_LegController_setIKLeg : public Callback_LegController_setIKLeg_Base, public ::IceInternal::OnewayCallbackNC<T>
{
public:

    typedef IceUtil::Handle<T> TPtr;

    typedef void (T::*Exception)(const ::Ice::Exception&);
    typedef void (T::*Sent)(bool);
    typedef void (T::*Response)();

    CallbackNC_LegController_setIKLeg(const TPtr& obj, Response cb, Exception excb, Sent sentcb)
        : ::IceInternal::OnewayCallbackNC<T>(obj, cb, excb, sentcb)
    {
    }
};

template<class T> Callback_LegController_setIKLegPtr
newCallback_LegController_setIKLeg(const IceUtil::Handle<T>& instance, void (T::*cb)(), void (T::*excb)(const ::Ice::Exception&), void (T::*sentcb)(bool) = 0)
{
    return new CallbackNC_LegController_setIKLeg<T>(instance, cb, excb, sentcb);
}

template<class T> Callback_LegController_setIKLegPtr
newCallback_LegController_setIKLeg(const IceUtil::Handle<T>& instance, void (T::*excb)(const ::Ice::Exception&), void (T::*sentcb)(bool) = 0)
{
    return new CallbackNC_LegController_setIKLeg<T>(instance, 0, excb, sentcb);
}

template<class T> Callback_LegController_setIKLegPtr
newCallback_LegController_setIKLeg(T* instance, void (T::*cb)(), void (T::*excb)(const ::Ice::Exception&), void (T::*sentcb)(bool) = 0)
{
    return new CallbackNC_LegController_setIKLeg<T>(instance, cb, excb, sentcb);
}

template<class T> Callback_LegController_setIKLegPtr
newCallback_LegController_setIKLeg(T* instance, void (T::*excb)(const ::Ice::Exception&), void (T::*sentcb)(bool) = 0)
{
    return new CallbackNC_LegController_setIKLeg<T>(instance, 0, excb, sentcb);
}

template<class T, typename CT>
class Callback_LegController_setIKLeg : public Callback_LegController_setIKLeg_Base, public ::IceInternal::OnewayCallback<T, CT>
{
public:

    typedef IceUtil::Handle<T> TPtr;

    typedef void (T::*Exception)(const ::Ice::Exception& , const CT&);
    typedef void (T::*Sent)(bool , const CT&);
    typedef void (T::*Response)(const CT&);

    Callback_LegController_setIKLeg(const TPtr& obj, Response cb, Exception excb, Sent sentcb)
        : ::IceInternal::OnewayCallback<T, CT>(obj, cb, excb, sentcb)
    {
    }
};

template<class T, typename CT> Callback_LegController_setIKLegPtr
newCallback_LegController_setIKLeg(const IceUtil::Handle<T>& instance, void (T::*cb)(const CT&), void (T::*excb)(const ::Ice::Exception&, const CT&), void (T::*sentcb)(bool, const CT&) = 0)
{
    return new Callback_LegController_setIKLeg<T, CT>(instance, cb, excb, sentcb);
}

template<class T, typename CT> Callback_LegController_setIKLegPtr
newCallback_LegController_setIKLeg(const IceUtil::Handle<T>& instance, void (T::*excb)(const ::Ice::Exception&, const CT&), void (T::*sentcb)(bool, const CT&) = 0)
{
    return new Callback_LegController_setIKLeg<T, CT>(instance, 0, excb, sentcb);
}

template<class T, typename CT> Callback_LegController_setIKLegPtr
newCallback_LegController_setIKLeg(T* instance, void (T::*cb)(const CT&), void (T::*excb)(const ::Ice::Exception&, const CT&), void (T::*sentcb)(bool, const CT&) = 0)
{
    return new Callback_LegController_setIKLeg<T, CT>(instance, cb, excb, sentcb);
}

template<class T, typename CT> Callback_LegController_setIKLegPtr
newCallback_LegController_setIKLeg(T* instance, void (T::*excb)(const ::Ice::Exception&, const CT&), void (T::*sentcb)(bool, const CT&) = 0)
{
    return new Callback_LegController_setIKLeg<T, CT>(instance, 0, excb, sentcb);
}

template<class T>
class CallbackNC_LegController_setIKBody : public Callback_LegController_setIKBody_Base, public ::IceInternal::OnewayCallbackNC<T>
{
public:

    typedef IceUtil::Handle<T> TPtr;

    typedef void (T::*Exception)(const ::Ice::Exception&);
    typedef void (T::*Sent)(bool);
    typedef void (T::*Response)();

    CallbackNC_LegController_setIKBody(const TPtr& obj, Response cb, Exception excb, Sent sentcb)
        : ::IceInternal::OnewayCallbackNC<T>(obj, cb, excb, sentcb)
    {
    }
};

template<class T> Callback_LegController_setIKBodyPtr
newCallback_LegController_setIKBody(const IceUtil::Handle<T>& instance, void (T::*cb)(), void (T::*excb)(const ::Ice::Exception&), void (T::*sentcb)(bool) = 0)
{
    return new CallbackNC_LegController_setIKBody<T>(instance, cb, excb, sentcb);
}

template<class T> Callback_LegController_setIKBodyPtr
newCallback_LegController_setIKBody(const IceUtil::Handle<T>& instance, void (T::*excb)(const ::Ice::Exception&), void (T::*sentcb)(bool) = 0)
{
    return new CallbackNC_LegController_setIKBody<T>(instance, 0, excb, sentcb);
}

template<class T> Callback_LegController_setIKBodyPtr
newCallback_LegController_setIKBody(T* instance, void (T::*cb)(), void (T::*excb)(const ::Ice::Exception&), void (T::*sentcb)(bool) = 0)
{
    return new CallbackNC_LegController_setIKBody<T>(instance, cb, excb, sentcb);
}

template<class T> Callback_LegController_setIKBodyPtr
newCallback_LegController_setIKBody(T* instance, void (T::*excb)(const ::Ice::Exception&), void (T::*sentcb)(bool) = 0)
{
    return new CallbackNC_LegController_setIKBody<T>(instance, 0, excb, sentcb);
}

template<class T, typename CT>
class Callback_LegController_setIKBody : public Callback_LegController_setIKBody_Base, public ::IceInternal::OnewayCallback<T, CT>
{
public:

    typedef IceUtil::Handle<T> TPtr;

    typedef void (T::*Exception)(const ::Ice::Exception& , const CT&);
    typedef void (T::*Sent)(bool , const CT&);
    typedef void (T::*Response)(const CT&);

    Callback_LegController_setIKBody(const TPtr& obj, Response cb, Exception excb, Sent sentcb)
        : ::IceInternal::OnewayCallback<T, CT>(obj, cb, excb, sentcb)
    {
    }
};

template<class T, typename CT> Callback_LegController_setIKBodyPtr
newCallback_LegController_setIKBody(const IceUtil::Handle<T>& instance, void (T::*cb)(const CT&), void (T::*excb)(const ::Ice::Exception&, const CT&), void (T::*sentcb)(bool, const CT&) = 0)
{
    return new Callback_LegController_setIKBody<T, CT>(instance, cb, excb, sentcb);
}

template<class T, typename CT> Callback_LegController_setIKBodyPtr
newCallback_LegController_setIKBody(const IceUtil::Handle<T>& instance, void (T::*excb)(const ::Ice::Exception&, const CT&), void (T::*sentcb)(bool, const CT&) = 0)
{
    return new Callback_LegController_setIKBody<T, CT>(instance, 0, excb, sentcb);
}

template<class T, typename CT> Callback_LegController_setIKBodyPtr
newCallback_LegController_setIKBody(T* instance, void (T::*cb)(const CT&), void (T::*excb)(const ::Ice::Exception&, const CT&), void (T::*sentcb)(bool, const CT&) = 0)
{
    return new Callback_LegController_setIKBody<T, CT>(instance, cb, excb, sentcb);
}

template<class T, typename CT> Callback_LegController_setIKBodyPtr
newCallback_LegController_setIKBody(T* instance, void (T::*excb)(const ::Ice::Exception&, const CT&), void (T::*sentcb)(bool, const CT&) = 0)
{
    return new Callback_LegController_setIKBody<T, CT>(instance, 0, excb, sentcb);
}

template<class T>
class CallbackNC_LegController_setFKLeg : public Callback_LegController_setFKLeg_Base, public ::IceInternal::OnewayCallbackNC<T>
{
public:

    typedef IceUtil::Handle<T> TPtr;

    typedef void (T::*Exception)(const ::Ice::Exception&);
    typedef void (T::*Sent)(bool);
    typedef void (T::*Response)();

    CallbackNC_LegController_setFKLeg(const TPtr& obj, Response cb, Exception excb, Sent sentcb)
        : ::IceInternal::OnewayCallbackNC<T>(obj, cb, excb, sentcb)
    {
    }
};

template<class T> Callback_LegController_setFKLegPtr
newCallback_LegController_setFKLeg(const IceUtil::Handle<T>& instance, void (T::*cb)(), void (T::*excb)(const ::Ice::Exception&), void (T::*sentcb)(bool) = 0)
{
    return new CallbackNC_LegController_setFKLeg<T>(instance, cb, excb, sentcb);
}

template<class T> Callback_LegController_setFKLegPtr
newCallback_LegController_setFKLeg(const IceUtil::Handle<T>& instance, void (T::*excb)(const ::Ice::Exception&), void (T::*sentcb)(bool) = 0)
{
    return new CallbackNC_LegController_setFKLeg<T>(instance, 0, excb, sentcb);
}

template<class T> Callback_LegController_setFKLegPtr
newCallback_LegController_setFKLeg(T* instance, void (T::*cb)(), void (T::*excb)(const ::Ice::Exception&), void (T::*sentcb)(bool) = 0)
{
    return new CallbackNC_LegController_setFKLeg<T>(instance, cb, excb, sentcb);
}

template<class T> Callback_LegController_setFKLegPtr
newCallback_LegController_setFKLeg(T* instance, void (T::*excb)(const ::Ice::Exception&), void (T::*sentcb)(bool) = 0)
{
    return new CallbackNC_LegController_setFKLeg<T>(instance, 0, excb, sentcb);
}

template<class T, typename CT>
class Callback_LegController_setFKLeg : public Callback_LegController_setFKLeg_Base, public ::IceInternal::OnewayCallback<T, CT>
{
public:

    typedef IceUtil::Handle<T> TPtr;

    typedef void (T::*Exception)(const ::Ice::Exception& , const CT&);
    typedef void (T::*Sent)(bool , const CT&);
    typedef void (T::*Response)(const CT&);

    Callback_LegController_setFKLeg(const TPtr& obj, Response cb, Exception excb, Sent sentcb)
        : ::IceInternal::OnewayCallback<T, CT>(obj, cb, excb, sentcb)
    {
    }
};

template<class T, typename CT> Callback_LegController_setFKLegPtr
newCallback_LegController_setFKLeg(const IceUtil::Handle<T>& instance, void (T::*cb)(const CT&), void (T::*excb)(const ::Ice::Exception&, const CT&), void (T::*sentcb)(bool, const CT&) = 0)
{
    return new Callback_LegController_setFKLeg<T, CT>(instance, cb, excb, sentcb);
}

template<class T, typename CT> Callback_LegController_setFKLegPtr
newCallback_LegController_setFKLeg(const IceUtil::Handle<T>& instance, void (T::*excb)(const ::Ice::Exception&, const CT&), void (T::*sentcb)(bool, const CT&) = 0)
{
    return new Callback_LegController_setFKLeg<T, CT>(instance, 0, excb, sentcb);
}

template<class T, typename CT> Callback_LegController_setFKLegPtr
newCallback_LegController_setFKLeg(T* instance, void (T::*cb)(const CT&), void (T::*excb)(const ::Ice::Exception&, const CT&), void (T::*sentcb)(bool, const CT&) = 0)
{
    return new Callback_LegController_setFKLeg<T, CT>(instance, cb, excb, sentcb);
}

template<class T, typename CT> Callback_LegController_setFKLegPtr
newCallback_LegController_setFKLeg(T* instance, void (T::*excb)(const ::Ice::Exception&, const CT&), void (T::*sentcb)(bool, const CT&) = 0)
{
    return new Callback_LegController_setFKLeg<T, CT>(instance, 0, excb, sentcb);
}

template<class T>
class CallbackNC_LegController_getStateLeg : public Callback_LegController_getStateLeg_Base, public ::IceInternal::TwowayCallbackNC<T>
{
public:

    typedef IceUtil::Handle<T> TPtr;

    typedef void (T::*Exception)(const ::Ice::Exception&);
    typedef void (T::*Sent)(bool);
    typedef void (T::*Response)(const ::RoboCompLegController::StateLeg&);

    CallbackNC_LegController_getStateLeg(const TPtr& obj, Response cb, Exception excb, Sent sentcb)
        : ::IceInternal::TwowayCallbackNC<T>(obj, cb != 0, excb, sentcb), response(cb)
    {
    }

    virtual void __completed(const ::Ice::AsyncResultPtr& __result) const
    {
        ::RoboCompLegController::LegControllerPrx __proxy = ::RoboCompLegController::LegControllerPrx::uncheckedCast(__result->getProxy());
        ::RoboCompLegController::StateLeg __ret;
        try
        {
            __ret = __proxy->end_getStateLeg(__result);
        }
        catch(::Ice::Exception& ex)
        {
            ::IceInternal::CallbackNC<T>::__exception(__result, ex);
            return;
        }
        if(response)
        {
            (::IceInternal::CallbackNC<T>::callback.get()->*response)(__ret);
        }
    }

    Response response;
};

template<class T> Callback_LegController_getStateLegPtr
newCallback_LegController_getStateLeg(const IceUtil::Handle<T>& instance, void (T::*cb)(const ::RoboCompLegController::StateLeg&), void (T::*excb)(const ::Ice::Exception&), void (T::*sentcb)(bool) = 0)
{
    return new CallbackNC_LegController_getStateLeg<T>(instance, cb, excb, sentcb);
}

template<class T> Callback_LegController_getStateLegPtr
newCallback_LegController_getStateLeg(T* instance, void (T::*cb)(const ::RoboCompLegController::StateLeg&), void (T::*excb)(const ::Ice::Exception&), void (T::*sentcb)(bool) = 0)
{
    return new CallbackNC_LegController_getStateLeg<T>(instance, cb, excb, sentcb);
}

template<class T, typename CT>
class Callback_LegController_getStateLeg : public Callback_LegController_getStateLeg_Base, public ::IceInternal::TwowayCallback<T, CT>
{
public:

    typedef IceUtil::Handle<T> TPtr;

    typedef void (T::*Exception)(const ::Ice::Exception& , const CT&);
    typedef void (T::*Sent)(bool , const CT&);
    typedef void (T::*Response)(const ::RoboCompLegController::StateLeg&, const CT&);

    Callback_LegController_getStateLeg(const TPtr& obj, Response cb, Exception excb, Sent sentcb)
        : ::IceInternal::TwowayCallback<T, CT>(obj, cb != 0, excb, sentcb), response(cb)
    {
    }

    virtual void __completed(const ::Ice::AsyncResultPtr& __result) const
    {
        ::RoboCompLegController::LegControllerPrx __proxy = ::RoboCompLegController::LegControllerPrx::uncheckedCast(__result->getProxy());
        ::RoboCompLegController::StateLeg __ret;
        try
        {
            __ret = __proxy->end_getStateLeg(__result);
        }
        catch(::Ice::Exception& ex)
        {
            ::IceInternal::Callback<T, CT>::__exception(__result, ex);
            return;
        }
        if(response)
        {
            (::IceInternal::Callback<T, CT>::callback.get()->*response)(__ret, CT::dynamicCast(__result->getCookie()));
        }
    }

    Response response;
};

template<class T, typename CT> Callback_LegController_getStateLegPtr
newCallback_LegController_getStateLeg(const IceUtil::Handle<T>& instance, void (T::*cb)(const ::RoboCompLegController::StateLeg&, const CT&), void (T::*excb)(const ::Ice::Exception&, const CT&), void (T::*sentcb)(bool, const CT&) = 0)
{
    return new Callback_LegController_getStateLeg<T, CT>(instance, cb, excb, sentcb);
}

template<class T, typename CT> Callback_LegController_getStateLegPtr
newCallback_LegController_getStateLeg(T* instance, void (T::*cb)(const ::RoboCompLegController::StateLeg&, const CT&), void (T::*excb)(const ::Ice::Exception&, const CT&), void (T::*sentcb)(bool, const CT&) = 0)
{
    return new Callback_LegController_getStateLeg<T, CT>(instance, cb, excb, sentcb);
}

}

#endif
