/* This file is autogenerated, do not edit*/
#include "moc_q4serialport.cpp"
#include "moc_commonbehaviorI.cpp"
#include "moc_footpreassuresensorI.cpp"
#include "moc_genericmonitor.cpp"
#include "moc_genericworker.cpp"
#include "moc_specificmonitor.cpp"
#include "moc_specificworker.cpp"
