// **********************************************************************
//
// Copyright (c) 2003-2013 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.5.1
//
// <auto-generated>
//
// Generated from file `FootPreassureSensor.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

#include <FootPreassureSensor.h>
#include <Ice/LocalException.h>
#include <Ice/ObjectFactory.h>
#include <Ice/BasicStream.h>
#include <Ice/Object.h>
#include <IceUtil/Iterator.h>

#ifndef ICE_IGNORE_VERSION
#   if ICE_INT_VERSION / 100 != 305
#       error Ice version mismatch!
#   endif
#   if ICE_INT_VERSION % 100 > 50
#       error Beta header file detected
#   endif
#   if ICE_INT_VERSION % 100 < 1
#       error Ice patch level mismatch!
#   endif
#endif

namespace
{

const ::std::string __RoboCompFootPreassureSensor__FootPreassureSensor__readSensors_name = "readSensors";

const ::std::string __RoboCompFootPreassureSensor__FootPreassureSensor__readSensor_name = "readSensor";

}
::IceProxy::Ice::Object* ::IceProxy::RoboCompFootPreassureSensor::upCast(::IceProxy::RoboCompFootPreassureSensor::FootPreassureSensor* p) { return p; }

void
::IceProxy::RoboCompFootPreassureSensor::__read(::IceInternal::BasicStream* __is, ::IceInternal::ProxyHandle< ::IceProxy::RoboCompFootPreassureSensor::FootPreassureSensor>& v)
{
    ::Ice::ObjectPrx proxy;
    __is->read(proxy);
    if(!proxy)
    {
        v = 0;
    }
    else
    {
        v = new ::IceProxy::RoboCompFootPreassureSensor::FootPreassureSensor;
        v->__copyFrom(proxy);
    }
}

::RoboCompFootPreassureSensor::Buffer
IceProxy::RoboCompFootPreassureSensor::FootPreassureSensor::readSensors(const ::Ice::Context* __ctx)
{
    ::IceInternal::InvocationObserver __observer(this, __RoboCompFootPreassureSensor__FootPreassureSensor__readSensors_name, __ctx);
    int __cnt = 0;
    while(true)
    {
        ::IceInternal::Handle< ::IceDelegate::Ice::Object> __delBase;
        try
        {
            __checkTwowayOnly(__RoboCompFootPreassureSensor__FootPreassureSensor__readSensors_name);
            __delBase = __getDelegate(false);
            ::IceDelegate::RoboCompFootPreassureSensor::FootPreassureSensor* __del = dynamic_cast< ::IceDelegate::RoboCompFootPreassureSensor::FootPreassureSensor*>(__delBase.get());
            return __del->readSensors(__ctx, __observer);
        }
        catch(const ::IceInternal::LocalExceptionWrapper& __ex)
        {
            __handleExceptionWrapper(__delBase, __ex, __observer);
        }
        catch(const ::Ice::LocalException& __ex)
        {
            __handleException(__delBase, __ex, true, __cnt, __observer);
        }
    }
}

::Ice::AsyncResultPtr
IceProxy::RoboCompFootPreassureSensor::FootPreassureSensor::begin_readSensors(const ::Ice::Context* __ctx, const ::IceInternal::CallbackBasePtr& __del, const ::Ice::LocalObjectPtr& __cookie)
{
    __checkAsyncTwowayOnly(__RoboCompFootPreassureSensor__FootPreassureSensor__readSensors_name);
    ::IceInternal::OutgoingAsyncPtr __result = new ::IceInternal::OutgoingAsync(this, __RoboCompFootPreassureSensor__FootPreassureSensor__readSensors_name, __del, __cookie);
    try
    {
        __result->__prepare(__RoboCompFootPreassureSensor__FootPreassureSensor__readSensors_name, ::Ice::Normal, __ctx);
        __result->__writeEmptyParams();
        __result->__send(true);
    }
    catch(const ::Ice::LocalException& __ex)
    {
        __result->__exceptionAsync(__ex);
    }
    return __result;
}

::RoboCompFootPreassureSensor::Buffer
IceProxy::RoboCompFootPreassureSensor::FootPreassureSensor::end_readSensors(const ::Ice::AsyncResultPtr& __result)
{
    ::Ice::AsyncResult::__check(__result, this, __RoboCompFootPreassureSensor__FootPreassureSensor__readSensors_name);
    ::RoboCompFootPreassureSensor::Buffer __ret;
    bool __ok = __result->__wait();
    try
    {
        if(!__ok)
        {
            try
            {
                __result->__throwUserException();
            }
            catch(const ::Ice::UserException& __ex)
            {
                throw ::Ice::UnknownUserException(__FILE__, __LINE__, __ex.ice_name());
            }
        }
        ::IceInternal::BasicStream* __is = __result->__startReadParams();
        __is->read(__ret);
        __result->__endReadParams();
        return __ret;
    }
    catch(const ::Ice::LocalException& ex)
    {
        __result->__getObserver().failed(ex.ice_name());
        throw;
    }
}

::Ice::Int
IceProxy::RoboCompFootPreassureSensor::FootPreassureSensor::readSensor(const ::std::string& name, const ::Ice::Context* __ctx)
{
    ::IceInternal::InvocationObserver __observer(this, __RoboCompFootPreassureSensor__FootPreassureSensor__readSensor_name, __ctx);
    int __cnt = 0;
    while(true)
    {
        ::IceInternal::Handle< ::IceDelegate::Ice::Object> __delBase;
        try
        {
            __checkTwowayOnly(__RoboCompFootPreassureSensor__FootPreassureSensor__readSensor_name);
            __delBase = __getDelegate(false);
            ::IceDelegate::RoboCompFootPreassureSensor::FootPreassureSensor* __del = dynamic_cast< ::IceDelegate::RoboCompFootPreassureSensor::FootPreassureSensor*>(__delBase.get());
            return __del->readSensor(name, __ctx, __observer);
        }
        catch(const ::IceInternal::LocalExceptionWrapper& __ex)
        {
            __handleExceptionWrapper(__delBase, __ex, __observer);
        }
        catch(const ::Ice::LocalException& __ex)
        {
            __handleException(__delBase, __ex, true, __cnt, __observer);
        }
    }
}

::Ice::AsyncResultPtr
IceProxy::RoboCompFootPreassureSensor::FootPreassureSensor::begin_readSensor(const ::std::string& name, const ::Ice::Context* __ctx, const ::IceInternal::CallbackBasePtr& __del, const ::Ice::LocalObjectPtr& __cookie)
{
    __checkAsyncTwowayOnly(__RoboCompFootPreassureSensor__FootPreassureSensor__readSensor_name);
    ::IceInternal::OutgoingAsyncPtr __result = new ::IceInternal::OutgoingAsync(this, __RoboCompFootPreassureSensor__FootPreassureSensor__readSensor_name, __del, __cookie);
    try
    {
        __result->__prepare(__RoboCompFootPreassureSensor__FootPreassureSensor__readSensor_name, ::Ice::Normal, __ctx);
        ::IceInternal::BasicStream* __os = __result->__startWriteParams(::Ice::DefaultFormat);
        __os->write(name);
        __result->__endWriteParams();
        __result->__send(true);
    }
    catch(const ::Ice::LocalException& __ex)
    {
        __result->__exceptionAsync(__ex);
    }
    return __result;
}

::Ice::Int
IceProxy::RoboCompFootPreassureSensor::FootPreassureSensor::end_readSensor(const ::Ice::AsyncResultPtr& __result)
{
    ::Ice::AsyncResult::__check(__result, this, __RoboCompFootPreassureSensor__FootPreassureSensor__readSensor_name);
    ::Ice::Int __ret;
    bool __ok = __result->__wait();
    try
    {
        if(!__ok)
        {
            try
            {
                __result->__throwUserException();
            }
            catch(const ::Ice::UserException& __ex)
            {
                throw ::Ice::UnknownUserException(__FILE__, __LINE__, __ex.ice_name());
            }
        }
        ::IceInternal::BasicStream* __is = __result->__startReadParams();
        __is->read(__ret);
        __result->__endReadParams();
        return __ret;
    }
    catch(const ::Ice::LocalException& ex)
    {
        __result->__getObserver().failed(ex.ice_name());
        throw;
    }
}

const ::std::string&
IceProxy::RoboCompFootPreassureSensor::FootPreassureSensor::ice_staticId()
{
    return ::RoboCompFootPreassureSensor::FootPreassureSensor::ice_staticId();
}

::IceInternal::Handle< ::IceDelegateM::Ice::Object>
IceProxy::RoboCompFootPreassureSensor::FootPreassureSensor::__createDelegateM()
{
    return ::IceInternal::Handle< ::IceDelegateM::Ice::Object>(new ::IceDelegateM::RoboCompFootPreassureSensor::FootPreassureSensor);
}

::IceInternal::Handle< ::IceDelegateD::Ice::Object>
IceProxy::RoboCompFootPreassureSensor::FootPreassureSensor::__createDelegateD()
{
    return ::IceInternal::Handle< ::IceDelegateD::Ice::Object>(new ::IceDelegateD::RoboCompFootPreassureSensor::FootPreassureSensor);
}

::IceProxy::Ice::Object*
IceProxy::RoboCompFootPreassureSensor::FootPreassureSensor::__newInstance() const
{
    return new FootPreassureSensor;
}

::RoboCompFootPreassureSensor::Buffer
IceDelegateM::RoboCompFootPreassureSensor::FootPreassureSensor::readSensors(const ::Ice::Context* __context, ::IceInternal::InvocationObserver& __observer)
{
    ::IceInternal::Outgoing __og(__handler.get(), __RoboCompFootPreassureSensor__FootPreassureSensor__readSensors_name, ::Ice::Normal, __context, __observer);
    __og.writeEmptyParams();
    bool __ok = __og.invoke();
    ::RoboCompFootPreassureSensor::Buffer __ret;
    try
    {
        if(!__ok)
        {
            try
            {
                __og.throwUserException();
            }
            catch(const ::Ice::UserException& __ex)
            {
                ::Ice::UnknownUserException __uue(__FILE__, __LINE__, __ex.ice_name());
                throw __uue;
            }
        }
        ::IceInternal::BasicStream* __is = __og.startReadParams();
        __is->read(__ret);
        __og.endReadParams();
        return __ret;
    }
    catch(const ::Ice::LocalException& __ex)
    {
        throw ::IceInternal::LocalExceptionWrapper(__ex, false);
    }
}

::Ice::Int
IceDelegateM::RoboCompFootPreassureSensor::FootPreassureSensor::readSensor(const ::std::string& name, const ::Ice::Context* __context, ::IceInternal::InvocationObserver& __observer)
{
    ::IceInternal::Outgoing __og(__handler.get(), __RoboCompFootPreassureSensor__FootPreassureSensor__readSensor_name, ::Ice::Normal, __context, __observer);
    try
    {
        ::IceInternal::BasicStream* __os = __og.startWriteParams(::Ice::DefaultFormat);
        __os->write(name);
        __og.endWriteParams();
    }
    catch(const ::Ice::LocalException& __ex)
    {
        __og.abort(__ex);
    }
    bool __ok = __og.invoke();
    ::Ice::Int __ret;
    try
    {
        if(!__ok)
        {
            try
            {
                __og.throwUserException();
            }
            catch(const ::Ice::UserException& __ex)
            {
                ::Ice::UnknownUserException __uue(__FILE__, __LINE__, __ex.ice_name());
                throw __uue;
            }
        }
        ::IceInternal::BasicStream* __is = __og.startReadParams();
        __is->read(__ret);
        __og.endReadParams();
        return __ret;
    }
    catch(const ::Ice::LocalException& __ex)
    {
        throw ::IceInternal::LocalExceptionWrapper(__ex, false);
    }
}

::RoboCompFootPreassureSensor::Buffer
IceDelegateD::RoboCompFootPreassureSensor::FootPreassureSensor::readSensors(const ::Ice::Context* __context, ::IceInternal::InvocationObserver&)
{
    class _DirectI : public ::IceInternal::Direct
    {
    public:

        _DirectI(::RoboCompFootPreassureSensor::Buffer& __result, const ::Ice::Current& __current) : 
            ::IceInternal::Direct(__current),
            _result(__result)
        {
        }
        
        virtual ::Ice::DispatchStatus
        run(::Ice::Object* object)
        {
            ::RoboCompFootPreassureSensor::FootPreassureSensor* servant = dynamic_cast< ::RoboCompFootPreassureSensor::FootPreassureSensor*>(object);
            if(!servant)
            {
                throw ::Ice::OperationNotExistException(__FILE__, __LINE__, _current.id, _current.facet, _current.operation);
            }
            _result = servant->readSensors(_current);
            return ::Ice::DispatchOK;
        }
        
    private:
        
        ::RoboCompFootPreassureSensor::Buffer& _result;
    };
    
    ::Ice::Current __current;
    __initCurrent(__current, __RoboCompFootPreassureSensor__FootPreassureSensor__readSensors_name, ::Ice::Normal, __context);
    ::RoboCompFootPreassureSensor::Buffer __result;
    try
    {
        _DirectI __direct(__result, __current);
        try
        {
            __direct.getServant()->__collocDispatch(__direct);
        }
        catch(...)
        {
            __direct.destroy();
            throw;
        }
        __direct.destroy();
    }
    catch(const ::Ice::SystemException&)
    {
        throw;
    }
    catch(const ::IceInternal::LocalExceptionWrapper&)
    {
        throw;
    }
    catch(const ::std::exception& __ex)
    {
        ::IceInternal::LocalExceptionWrapper::throwWrapper(__ex);
    }
    catch(...)
    {
        throw ::IceInternal::LocalExceptionWrapper(::Ice::UnknownException(__FILE__, __LINE__, "unknown c++ exception"), false);
    }
    return __result;
}

::Ice::Int
IceDelegateD::RoboCompFootPreassureSensor::FootPreassureSensor::readSensor(const ::std::string& name, const ::Ice::Context* __context, ::IceInternal::InvocationObserver&)
{
    class _DirectI : public ::IceInternal::Direct
    {
    public:

        _DirectI(::Ice::Int& __result, const ::std::string& __p_name, const ::Ice::Current& __current) : 
            ::IceInternal::Direct(__current),
            _result(__result),
            _m_name(__p_name)
        {
        }
        
        virtual ::Ice::DispatchStatus
        run(::Ice::Object* object)
        {
            ::RoboCompFootPreassureSensor::FootPreassureSensor* servant = dynamic_cast< ::RoboCompFootPreassureSensor::FootPreassureSensor*>(object);
            if(!servant)
            {
                throw ::Ice::OperationNotExistException(__FILE__, __LINE__, _current.id, _current.facet, _current.operation);
            }
            _result = servant->readSensor(_m_name, _current);
            return ::Ice::DispatchOK;
        }
        
    private:
        
        ::Ice::Int& _result;
        const ::std::string& _m_name;
    };
    
    ::Ice::Current __current;
    __initCurrent(__current, __RoboCompFootPreassureSensor__FootPreassureSensor__readSensor_name, ::Ice::Normal, __context);
    ::Ice::Int __result;
    try
    {
        _DirectI __direct(__result, name, __current);
        try
        {
            __direct.getServant()->__collocDispatch(__direct);
        }
        catch(...)
        {
            __direct.destroy();
            throw;
        }
        __direct.destroy();
    }
    catch(const ::Ice::SystemException&)
    {
        throw;
    }
    catch(const ::IceInternal::LocalExceptionWrapper&)
    {
        throw;
    }
    catch(const ::std::exception& __ex)
    {
        ::IceInternal::LocalExceptionWrapper::throwWrapper(__ex);
    }
    catch(...)
    {
        throw ::IceInternal::LocalExceptionWrapper(::Ice::UnknownException(__FILE__, __LINE__, "unknown c++ exception"), false);
    }
    return __result;
}

::Ice::Object* RoboCompFootPreassureSensor::upCast(::RoboCompFootPreassureSensor::FootPreassureSensor* p) { return p; }

namespace
{
const ::std::string __RoboCompFootPreassureSensor__FootPreassureSensor_ids[2] =
{
    "::Ice::Object",
    "::RoboCompFootPreassureSensor::FootPreassureSensor"
};

}

bool
RoboCompFootPreassureSensor::FootPreassureSensor::ice_isA(const ::std::string& _s, const ::Ice::Current&) const
{
    return ::std::binary_search(__RoboCompFootPreassureSensor__FootPreassureSensor_ids, __RoboCompFootPreassureSensor__FootPreassureSensor_ids + 2, _s);
}

::std::vector< ::std::string>
RoboCompFootPreassureSensor::FootPreassureSensor::ice_ids(const ::Ice::Current&) const
{
    return ::std::vector< ::std::string>(&__RoboCompFootPreassureSensor__FootPreassureSensor_ids[0], &__RoboCompFootPreassureSensor__FootPreassureSensor_ids[2]);
}

const ::std::string&
RoboCompFootPreassureSensor::FootPreassureSensor::ice_id(const ::Ice::Current&) const
{
    return __RoboCompFootPreassureSensor__FootPreassureSensor_ids[1];
}

const ::std::string&
RoboCompFootPreassureSensor::FootPreassureSensor::ice_staticId()
{
    return __RoboCompFootPreassureSensor__FootPreassureSensor_ids[1];
}

::Ice::DispatchStatus
RoboCompFootPreassureSensor::FootPreassureSensor::___readSensors(::IceInternal::Incoming& __inS, const ::Ice::Current& __current)
{
    __checkMode(::Ice::Normal, __current.mode);
    __inS.readEmptyParams();
    ::RoboCompFootPreassureSensor::Buffer __ret = readSensors(__current);
    ::IceInternal::BasicStream* __os = __inS.__startWriteParams(::Ice::DefaultFormat);
    __os->write(__ret);
    __inS.__endWriteParams(true);
    return ::Ice::DispatchOK;
}

::Ice::DispatchStatus
RoboCompFootPreassureSensor::FootPreassureSensor::___readSensor(::IceInternal::Incoming& __inS, const ::Ice::Current& __current)
{
    __checkMode(::Ice::Normal, __current.mode);
    ::IceInternal::BasicStream* __is = __inS.startReadParams();
    ::std::string name;
    __is->read(name);
    __inS.endReadParams();
    ::Ice::Int __ret = readSensor(name, __current);
    ::IceInternal::BasicStream* __os = __inS.__startWriteParams(::Ice::DefaultFormat);
    __os->write(__ret);
    __inS.__endWriteParams(true);
    return ::Ice::DispatchOK;
}

namespace
{
const ::std::string __RoboCompFootPreassureSensor__FootPreassureSensor_all[] =
{
    "ice_id",
    "ice_ids",
    "ice_isA",
    "ice_ping",
    "readSensor",
    "readSensors"
};

}

::Ice::DispatchStatus
RoboCompFootPreassureSensor::FootPreassureSensor::__dispatch(::IceInternal::Incoming& in, const ::Ice::Current& current)
{
    ::std::pair< const ::std::string*, const ::std::string*> r = ::std::equal_range(__RoboCompFootPreassureSensor__FootPreassureSensor_all, __RoboCompFootPreassureSensor__FootPreassureSensor_all + 6, current.operation);
    if(r.first == r.second)
    {
        throw ::Ice::OperationNotExistException(__FILE__, __LINE__, current.id, current.facet, current.operation);
    }

    switch(r.first - __RoboCompFootPreassureSensor__FootPreassureSensor_all)
    {
        case 0:
        {
            return ___ice_id(in, current);
        }
        case 1:
        {
            return ___ice_ids(in, current);
        }
        case 2:
        {
            return ___ice_isA(in, current);
        }
        case 3:
        {
            return ___ice_ping(in, current);
        }
        case 4:
        {
            return ___readSensor(in, current);
        }
        case 5:
        {
            return ___readSensors(in, current);
        }
    }

    assert(false);
    throw ::Ice::OperationNotExistException(__FILE__, __LINE__, current.id, current.facet, current.operation);
}

void
RoboCompFootPreassureSensor::FootPreassureSensor::__writeImpl(::IceInternal::BasicStream* __os) const
{
    __os->startWriteSlice(ice_staticId(), -1, true);
    __os->endWriteSlice();
}

void
RoboCompFootPreassureSensor::FootPreassureSensor::__readImpl(::IceInternal::BasicStream* __is)
{
    __is->startReadSlice();
    __is->endReadSlice();
}

void 
RoboCompFootPreassureSensor::__patch(FootPreassureSensorPtr& handle, const ::Ice::ObjectPtr& v)
{
    handle = ::RoboCompFootPreassureSensor::FootPreassureSensorPtr::dynamicCast(v);
    if(v && !handle)
    {
        IceInternal::Ex::throwUOE(::RoboCompFootPreassureSensor::FootPreassureSensor::ice_staticId(), v);
    }
}
